changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: Application Image Compilation
      labels:
        - application-image
        - enhancement
    - title: Security and hardening
      labels:
        - security
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Other changes
      labels:
        - "*"
